### ISSUE TITLE
Why do u use Spring state machinre

### ISSUE THREAD

**Issue by HelloTo4x** [Tahauddin-Syed/Spring-State-Machine#1]
Hi, i am reading your project and i am interesting in your project, but i have a question, why do you use Spring state machine, can u tell the purpose, the pros and cons of Spring state machine, why don't u use other library

**Comment by Tahauddin-Syed** [comment]
Hi, 
If we want to track the state of the machine and persist it in DB, then we use this spring state machine, though we have some other library as well, but honestly i haven't tried.
The only thing i tried is this library, and in Microservice it is a good fit.
if you want to track the payment state or order state, then according to me, this is a great fit.

Best Regards,
Syed Tahauddin
